#!/bin/sh
# Regenerates gs_shaders.h (SPIR-V as C arrays) from gs.vert, gs.frag, gs_decode.comp, gs_overlay.comp, gs_unswizzle.comp, gs_display.comp, gs_display_rt.comp, gs_reinterpret.comp. Needs glslang
# (glslangValidator or glslang on PATH, or GLSLANG=/path/to/glslang).
set -e
cd "$(dirname "$0")"
G=${GLSLANG:-$(command -v glslangValidator || command -v glslang)}
"$G" -V --target-env vulkan1.3 --vn kGsVertSpv gs.vert -o gs_vert.h
"$G" -V --target-env vulkan1.3 --vn kGsFragSpv gs.frag -o gs_frag.h
"$G" -V --target-env vulkan1.3 -DDUAL_SRC --vn kGsFragDualSpv gs.frag -o gs_frag2.h
"$G" -V --target-env vulkan1.3 --vn kGsDecodeSpv gs_decode.comp -o gs_decode.h
"$G" -V --target-env vulkan1.3 --vn kGsOverlaySpv gs_overlay.comp -o gs_overlay.h
"$G" -V --target-env vulkan1.3 --vn kGsUnswizzleSpv gs_unswizzle.comp -o gs_unswizzle.h
"$G" -V --target-env vulkan1.3 --vn kGsDisplaySpv gs_display.comp -o gs_display.h
"$G" -V --target-env vulkan1.3 --vn kGsDisplayRtSpv gs_display_rt.comp -o gs_display_rt.h
"$G" -V --target-env vulkan1.3 --vn kGsReinterpretSpv gs_reinterpret.comp -o gs_reinterpret.h
{
  echo "// Generated by gen_shaders.sh from gs.vert, gs.frag, gs_decode.comp, gs_overlay.comp, gs_unswizzle.comp, gs_display.comp, gs_display_rt.comp, gs_reinterpret.comp - do not edit."
  echo "#pragma once"
  echo "#include <cstdint>"
  cat gs_vert.h gs_frag.h gs_frag2.h gs_decode.h gs_overlay.h gs_unswizzle.h gs_display.h gs_display_rt.h gs_reinterpret.h
} > gs_shaders.h
rm gs_vert.h gs_frag.h gs_frag2.h gs_decode.h gs_overlay.h gs_unswizzle.h gs_display.h gs_display_rt.h gs_reinterpret.h
