#!/bin/sh
# Regenerates gs_shaders.h (SPIR-V as C arrays) from gs.vert / gs.frag. Needs glslang
# (glslangValidator or glslang on PATH, or GLSLANG=/path/to/glslang).
set -e
cd "$(dirname "$0")"
G=${GLSLANG:-$(command -v glslangValidator || command -v glslang)}
"$G" -V --target-env vulkan1.3 --vn kGsVertSpv gs.vert -o gs_vert.h
"$G" -V --target-env vulkan1.3 --vn kGsFragSpv gs.frag -o gs_frag.h
"$G" -V --target-env vulkan1.3 -DDUAL_SRC --vn kGsFragDualSpv gs.frag -o gs_frag2.h
{
  echo "// Generated by gen_shaders.sh from gs.vert / gs.frag - do not edit."
  echo "#pragma once"
  echo "#include <cstdint>"
  cat gs_vert.h gs_frag.h gs_frag2.h
} > gs_shaders.h
rm gs_vert.h gs_frag.h gs_frag2.h
